steps:
  - name: 'node:22'
    entrypoint: bash
    args: 
      - -c
      - |
        npm ci

  - name: 'node:22'
    entrypoint: bash
    args:
      - -c
      - |
        npm run build

  - name: 'gcr.io/cloud-builders/gsutil'
    args: 
      [
           "-m",
           "rsync",
           "-r",
           "dist",
           "gs://react-nav/test-dist/"
           ]

options:
  logging: CLOUD_LOGGING_ONLY
